# Default values for Citrix Cloud Native Deployments.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cic: 
  enabled: False

cpx:
  enabled: False

cnc:
  enabled: False

coe:
  enabled: False

ia-ingress:
  enabled: False

ia-sidecar:
  enabled: False
