---
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: bookinfo-policy
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
{{- if eq .Values.mtlsEnabled true }}
    mode: STRICT
{{- else }}
    mode: DISABLE
{{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: productpage-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: "productpage"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: ratings-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: "ratings"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: details-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: "details"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: "reviews"
  trafficPolicy:
    tls:
{{- if eq .Values.mtlsEnabled true }}
      mode: ISTIO_MUTUAL
{{- else }} 
      mode: DISABLE
{{- end }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
